version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: smartcoin-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: .
      dockerfile: sc_server/Dockerfile
    container_name: smartcoin-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
